name: Playwright Tests

# 1. THE TRIGGER: When should this pipeline run?
on:
  push:
    branches: [ master ]      # Runs when code is merged to main
  pull_request:
    branches: [ master ]      # Runs when a PR is opened targeting main
  workflow_dispatch:

# 2. THE SERVER: Spin up a free Linux machine
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest  # 2. THE SERVER: Spin up a free Linux machine

    steps:
      # 3. DOWNLOAD YOUR CODE
      - uses: actions/checkout@v4

      # 4. INSTALL JAVA
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # 5. DOWNLOAD JAVA LIBRARIES (Playwright, TestNG, Faker)
      - name: Build and install Maven dependencies
        run: mvn -B install -DskipTests

      # 6. INSTALL THE BROWSERS (Chrome, Firefox, Safari)
      # The Linux machine needs the physical browsers installed to run the tests!
      - name: Install Playwright Browsers and System Dependencies
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"

      # 7. START DOCKER
      - name: Start Parabank Local Server (Docker)
        run: |
          docker run -d -p 8080:8080 parasoft/parabank
          echo "Waiting for Parabank server to be fully ready..."
          timeout 60s bash -c 'until [ "$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/parabank/index.htm)" == "200" ]; do sleep 2; done'

      # 8. RUN THE TESTS
      - name: Run TestNG Suite
        run: mvn test

      # 9. UPLOAD SCREENSHOTS AND REPORTS
      - name: Upload Failure Screenshots and Test Reports
        if: always() # Ensures reports are uploaded even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-failure-reports
          path: target/
          if-no-files-found: ignore
